export {default as Home} from './Home'
export {default as Chats} from './Chats'
export {default as Games} from './Games'
export {default as Profile} from './Profile'
export {default as UpdateProfile} from './UpdateProfile'
export {default as ManageUsers} from './ManageUsers'
export {default as ManagePlayers} from './ManagePlayers'